// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx } from 'react/jsx-runtime';
import ExampleResults from 'components/example/example-results';
import { fetchGraphQlExample } from 'lib/example/fetch/example.api';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
    ]
  },
  {
    module: 'components/example/example-results',
    exports: [
      { name: 'default', value: ExampleResults },
    ]
  },
  {
    module: 'lib/example/fetch/example.api',
    exports: [
      { name: 'fetchGraphQlExample', value: fetchGraphQlExample },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
